[package]
name = "pattterns"
version = "0.1.0"
authors = ["Szecsődi Imre <imre.szecsodi@l-mobile.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
